### ISSUE TITLE
Issue deploying precompiled project

### ISSUE THREAD

**Issue by lebster** [KenticoDevTrev/DynamicRouting#21]
@KenticoDevTrev 

I am having similar Issues as #10 . On my local everything works correctly (installed via nuget packages). On Test/Dev server the module was missing. We are deploying the MVC and CMS projects as precompiled projects from TFS to our dev servers. 

I tried importing as you suggested but the two options "Import code files" and "Import custom assembly files" are grayed out. It says importing assemblies and code files is disabled in precompiled web. I went ahead and hit next and now see dynamic routing in the menu but clicking rebuild site throws an error. 

```
Message: Exception of type 'System.Web.HttpUnhandledException' was thrown.

Exception type: System.Web.HttpUnhandledException
Stack trace:
at System.Web.UI.Page.HandleError(Exception e)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
at System.Web.UI.Page.ProcessRequest()
at System.Web.UI.Page.ProcessRequest(HttpContext context)
at ASP.cmsmodules_dynamicrouting_kentico_quickoperations_aspx.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Message: [DataClassInfoProvider.GetClassStructureInfoFromDB]: Class information for class 'DynamicRouting.UrlSlug' not found.

Exception type: CMS.DataEngine.DataClassNotFoundException
Stack trace:
at CMS.DataEngine.DataClassInfoProvider.GetClassStructureInfoFromDB(String className)
at CMS.DataEngine.ClassStructureInfo.GetClassInfo(String className)
at CMS.DataEngine.DataQueryBase`1.GetDefaultSource()
at CMS.DataEngine.DataQueryBase`1.EnsureDefaultSource(DataQuerySettings settings)
at CMS.DataEngine.DataQueryBase`1.GetCompleteSettings(IDataQuery executingQuery)
at CMS.DataEngine.ObjectQueryBase`2.GetExecutingQuery(DataQuerySettings settings)
at CMS.DataEngine.DataQueryBase`1.GetDataFromDB()
at CMS.DataEngine.DataQueryBase`1.GetData()
at CMS.DataEngine.ObjectQueryBase`2.GetData()
at CMS.DataEngine.DataQueryBase`1.get_Result()
at CMS.DataEngine.ObjectQueryBase`2.EnsureTypedResult()
at CMS.DataEngine.ObjectQueryBase`2.GetEnumerator()
at DynamicRouting.NodeItem.BuildUrlSlugs(Boolean UseCurrentVersion)
at DynamicRouting.NodeItem..ctor(Int32 PageNodeID, NodeItemBuilderSettings Settings, Boolean UseCurrentVersion)
at DynamicRouting.DynamicRouteInternalHelper.RebuildRoutesBySite(String SiteName)
at CMSApp.CMSModules.DynamicRouting.QuickOperations.btnRebuildSite_Click(Object sender, EventArgs e)
at System.Web.UI.WebControls.Button.OnClick(EventArgs e)
at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

I also noticed dynamic routing is missing from settings menu.

**Comment by KenticoDevTrev** [comment]
You will need to install the module on the other environment manually if your deployment is stripping out the install files.

Is there anyway to connect to the live database from a non pre compiled site and install that way? You really just need the database operations done.

This isn't really an issue with my module but any that you try to install this way.

**Comment by lebster** [comment]
Ok, I tried pointing my local env to the live database. I reinstalled the nuget package and still run into the same error. I then tried to import (which said it will overwrite existing package), and checked those two options previous unable to check. After that was done I still get the same error. 

Is there a script I can run to execute the database operations manually? 

Or maybe I can delete the module and try again. I tried to delete but it says it cannot be deleted because existing classes, settings ui elements, page types are assigned to this module.

**Comment by KenticoDevTrev** [comment]
shoot me an email tfayas@hbs.net, i'll see if i can spin up a webex quickly and see if i can help you get it installed.

**Comment by KenticoDevTrev** [comment]
We resolved the issue, we had to manually import just the Module itself by opening up the nuget package, going to the Content\App_Data\CMSModules\DynamicRouting.Kentico\Install and there is a zip file there that we went to Site -> Import site or object and did it there.
