### ISSUE TITLE
Page template not found for selected page.

### ISSUE THREAD

**Issue by liamgold** [KenticoDevTrev/DynamicRouting#32]
When you've got a page that uses advanced page templates, if you unpublished the page and visit the URL on the MVC front end, instead of getting a friendly 404 page (HttpErrors controller) you get an Error 500 stating:

```
Message: Page template not found for selected page.

Exception type: System.InvalidOperationException
Stack trace:
at Kentico.PageBuilder.Web.Mvc.PageTemplates.TemplateResult.ExecuteResultInternal(IActionInvoker invoker, ControllerContext context, PageTemplateConfiguration configuration)
at Kentico.PageBuilder.Web.Mvc.PageTemplates.TemplateResult.ExecuteResult(ControllerContext context)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
at System.Web.Mvc.Controller.ExecuteCore()
at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)
at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)
at DynamicRouting.Kentico.MVC.DynamicHttpHandler.ProcessRequest(HttpContext context) in H:\Web\KenticoRepositories\DynamicRouting\DynamicRouting.Kentico.MVC\DynamicHttpHandler.cs:line 93
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
``` 

This seems to be an issue with how the DynamicRouteHelper builds up the query for GetPage. See #31 for a change which appears to work fine for me.

**Comment by KenticoDevTrev** [comment]
Thanks, I'll incorporate the fix hopefully today and republish the package so you can use the nuget package. Appreciate you not only reporting but finding a solution!

**Comment by liamgold** [comment]
Thanks @KenticoDevTrev, please do let me know when it's updated and I'll apply to the couple sites that require this fixing 👍

**Comment by KenticoDevTrev** [comment]
Hey @liamgold , i took a look, and my code actually already had the documentID dependency...what version of dynamic routing are you on?

**Comment by liamgold** [comment]
Hi @KenticoDevTrev you've got an if condition which means if the page is not found and is null, there isn't a cache dependency for the document ID. So if a page is unpublished and you make a content change and publish the page, the page will stay cached as null. Does this make sense?

**Comment by KenticoDevTrev** [comment]
Once Nuget updates it's index, you can install 12.29.17! thanks again!
