### ISSUE TITLE
Problem with queue stopping processing

### ISSUE THREAD

**Issue by massimde** [KenticoDevTrev/DynamicRouting#43]
Hi,
I would like assistance on the following problem. Sometimes, when we massively create/update/publish Kentico elements (about 1000 elements), URL Slug generation queue stops processing with a NullReference exception without giving us any other troubleshooting details. In this situation, a very large queue is created and must be restarted manually. Have you experienced a similar situation before? 
Without further details it is difficult for us to solve problems because the situation occurs occasionally.
We are using Kentico 12 MVC and the library version is 12.29.18.
Thanks a lot,

**Comment by KenticoDevTrev** [comment]
Hmmm... I'm not sure off hand what could be wrong, what you can do is just download this repo and attach it to your project instead of the nugget package so you can debug.  There is also, if I remember, a function that you can rebuild a section of the tree, if the import is going and fails that, maybe just rebuild after?  Otherwise we should try a screen share to get things set up so you can debug

**Comment by KenticoDevTrev** [comment]
Email me tfayas @ hbs.net

**Comment by massimde** [comment]
Unfortunately, this situation occasionally occurs in production and it is not easy to reproduce it locally for debugging. Consider that the solution is hosted on Azure as a Web App Service and the DLLs are all compiled in Release. In case it happens again, we may share the screen as you suggest.

**Comment by KenticoDevTrev** [comment]
That can be hard. What you can do is first copy the azure database (very easy to copy it), then make sure your local instance can access it (firewall and add your ip temporarily), then you should be able to point to the copy instance from your local machine and run the task.

**Comment by massimde** [comment]
This would make sense if the URL generation system retried from the "breaking point", but if the stop occurs on an event, this approach may not work. Do you agree?

**Comment by KenticoDevTrev** [comment]
If you are running it locally and you have the Dynamic Routing project referenced, you should be able to try/catch around where the error is generating and put a breakpoint and run it still.  If the error's within Kentico's DLL's then it may get trickier, but still should be able to try/catch and at least get some more info on what's going wrong, i have source code of Kentico's libraries that i could assist further to help figure things out. 

Try that first though!  Need to be able to replicate and debug in order to pinpoint the issue.

**Comment by KenticoDevTrev** [comment]
Otherwise, although probably not 'ideal', if you upgrade to Kentico 13 they have a built in routing which will be more 'stable' as it's Kentico's own system, that's why Dynamic Routing doesn't have a version 13, they adopted and integrated my dynamic routing into the system (thankfully)

**Comment by massimde** [comment]
In that case I can try this approach. Thank you! I will keep you updated :-)

**Comment by massimde** [comment]
hi,
i got the error:

Message: Object reference not set to an instance of an object.

 
Exception type: System.NullReferenceException
Stack trace: 
   at DynamicRouting.NodeItem.BuildUrlSlugs(Boolean UseCurrentVersion)
   at DynamicRouting.NodeItem..ctor(NodeItem parent, TreeNode Node, NodeItemBuilderSettings Settings, Boolean BuildChildren)
   at DynamicRouting.NodeItem.BuildChildren()
   at DynamicRouting.DynamicRouteInternalHelper.RunSlugGenerationQueueItem()

The serialized node item is:

`<?xml version="1.0" encoding="utf-16"?>
<NodeItem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <NodeID>8252</NodeID>
  <UrlSlugs>
    <NodeUrlSlug>
      <CultureCode>de-DE</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>false</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>1c332f9f-b948-48ad-9296-e1bae63970f3</ExistingNodeSlugGuid>
    </NodeUrlSlug>
    <NodeUrlSlug>
      <CultureCode>en-US</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>true</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>9e543769-d8c6-4e2e-929c-96d7eae34794</ExistingNodeSlugGuid>
    </NodeUrlSlug>
    <NodeUrlSlug>
      <CultureCode>es-ES</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>false</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>f68bb49c-ff6f-4469-9603-ffad78c595de</ExistingNodeSlugGuid>
    </NodeUrlSlug>
    <NodeUrlSlug>
      <CultureCode>fr-FR</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>false</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>6cd2531f-8c4d-477b-acd7-62978b4bfcb1</ExistingNodeSlugGuid>
    </NodeUrlSlug>
    <NodeUrlSlug>
      <CultureCode>it-IT</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>false</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>8c2704ff-448f-49cc-9c60-1bae64f0293d</ExistingNodeSlugGuid>
    </NodeUrlSlug>
    <NodeUrlSlug>
      <CultureCode>ru-RU</CultureCode>
      <SiteID>1</SiteID>
      <UrlSlug>/Home/References/Hotel</UrlSlug>
      <IsDefault>false</IsDefault>
      <IsCustom>false</IsCustom>
      <IsNewOrUpdated>false</IsNewOrUpdated>
      <Delete>false</Delete>
      <ExistingNodeSlugGuid>9b48517d-75f0-4c4e-ad3f-afa885a5d667</ExistingNodeSlugGuid>
    </NodeUrlSlug>
  </UrlSlugs>
  <IsContainer>true</IsContainer>
  <SavedAlready>true</SavedAlready>
  <ClassName>XXX.ReferenceCategory</ClassName>
  <AlsoBuildNodeID>-1</AlsoBuildNodeID>
  <Settings>
    <SiteName>XXX</SiteName>
    <CultureCodes>
      <string>en-US</string>
      <string>fr-FR</string>
      <string>de-DE</string>
      <string>it-IT</string>
      <string>ru-RU</string>
      <string>es-ES</string>
    </CultureCodes>
    <DefaultCultureCode>en-US</DefaultCultureCode>
    <GenerateIfCultureDoesntExist>true</GenerateIfCultureDoesntExist>
    <CheckQueueImmediately>true</CheckQueueImmediately>
    <CheckingForUpdates>true</CheckingForUpdates>
    <BuildSiblings>false</BuildSiblings>
    <BuildChildren>false</BuildChildren>
    <BuildDescendents>false</BuildDescendents>
  </Settings>
  <Children />
  <ChildrenBuilt>true</ChildrenBuilt>
</NodeItem>`

and this is the screenshot:

![image](https://user-images.githubusercontent.com/43574269/134191754-aed88fda-9984-4968-b184-be1533c8b424.png)

unfortunately if i try to restart the task, the queue gets empty and i can't replicate the error, so i can't debug the issue.
